package com.auction.network;

public enum ActionType {
    //REQUEST
    LOGIN,
    REGISTER,
    PLACE_BID,
    CREATE_AUCTION,
    SHOW_AUCTION_LIST,
    //RESPONSE
    LOGIN_SUCCESS,
    LOGIN_FAILED,
    REGISTER_SUCCESS,
    REGISTER_FAILED,
    PLACE_BID_SUCCESS,
    PLACE_BID_FAILED,
    CREATE_AUCTION_SUCCESS,
    CREATE_AUCTION_FAILED,
    AUCTION_CLOSED,
    NOTIFY_NEW_BID,
    //COMMON
    ERROR,
    SUCCESS
}
