package com.auction.protocol;

public enum ActionType {
    //REQUEST
    LOGIN,
    REGISTER,
    PLACE_BID,
    CREATE_AUCTION,
    GET_AUCTION_LIST,
    //RESPONSE
    LOGIN_SUCCESS,
    LOGIN_FAILURE,
    REGISTER_SUCCESS,
    REGISTER_FAILURE,
    PLACE_BID_SUCCESS,
    PLACE_BID_FAILURE,
    CREATE_AUCTION_SUCCESS,
    CREATE_AUCTION_FAILURE,
    AUCTION_CLOSED,
    NOTIFY_NEW_BID,
    //COMMON
    ERROR,
    SUCCESS
}
